name: azbridge to dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ls
      run: |
        ls

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerBuild
      run: |
        wget https://github.com/Azure/azure-relay-bridge/releases/download/v0.15.0/azbridge-oci-image-0.15.0.tar
        docker load -i azbridge-oci-image-0.15.0.tar
        image="${{ secrets.DOCKERHUB_USERNAME }}/azbridge:0.15"
        echo  "--------- Images ---------"
        docker images
        docker tag azbridge:0.15 $image
        echo  "---- Images after TAG ----"
        docker images
        docker push $image
